### ISSUE TITLE
replace -_score with -score

### ISSUE THREAD

**Issue by stevemart** [IBM/watson-discovery-news#40]
we had a comment on an old PR [1] to replace `-_score` with `-score` in query_builder.py. The comment is still valid from a code point of view [2], but i'm not sure if it's a valid change/suggestion, so i'm filing this bug so we don't forget about it. 

[1] https://github.com/IBM/watson-discovery-news/commit/5230762109db924c6db695c0890451c3b7fcc257#commitcomment-26180042
[2] https://github.com/IBM/watson-discovery-news/blob/master/server/query-builder.js#L40

**Comment by rhagarty** [comment]
I just started seeing this issue in another Watson Discovery app which also used the '-_score' as the sort key. It returned the error "Error: [_score] unknown field [unmapped_type], parser not found".

Changing to '-score' fixed the problem.
