### ISSUE TITLE
Getting error with the code

### ISSUE THREAD

**Issue by pinoycoach** [IBM/watson-discovery-news#81]
Hi,

I tried deploying this on IBM and it doesn't work. I asked IBM support and they say there could be a problem with the code as they are getting the same result.

Thank you

**Comment by rhagarty** [comment]
@pinoycoach - please try again with latest version. I bumped the memory and set the node version to 8, which worked for me.

PR #82

**Comment by pinoycoach** [comment]
Hi, 

Thank you Rich. Will do just that.

cheers

**Comment by pinoycoach** [comment]
Hi Rich,

Just letting you know it worked! Thank you, now my challenge is to deploy it as a chatbot.

Will let IBM support that you have helped me.

cheers!
