### ISSUE TITLE
Deploy Local: Unauthorised: Access Denied

### ISSUE THREAD

**Issue by zacaintmyname** [IBM/watson-discovery-news#88]
Hi Team,

I encountered this problem when I tried to follow the Code Pattern Tutorial.
After step npm install and npm start.. 

Do you know why? :( 

> watson-discovery-news@1.0.0 start /Users/zacaintmyname/watson-discovery-news
> node --max_old_space_size=512 app.js

{ Unauthorized: Access is denied due to invalid credentials.
    at RequestWrapper.formatError (/Users/zacaintmyname/watson-discovery-news/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
    at /Users/zacaintmyname/watson-discovery-news/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  cause:
   { Unauthorized: Access is denied due to invalid credentials.
       at RequestWrapper.formatError (/Users/zacaintmyname/watson-discovery-news/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
       at /Users/zacaintmyname/watson-discovery-news/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
       at process._tickCallback (internal/process/next_tick.js:68:7)
     name: 'Unauthorized',
     code: 401,
     message: 'Access is denied due to invalid credentials.',
     body: '{"code":401,"error":"Unauthorized"}',
     headers:
      { 'x-backside-transport': 'FAIL FAIL',
        'content-type': 'application/json',
        'x-dp-transit-id': 'gateway02-695182633',
        'x-global-transaction-id': 'ffea405d5d770bbc296fa529',
        'strict-transport-security': 'max-age=31536000;',
        'x-dp-watson-tran-id': 'gateway02-695182633',
        'content-length': '37',
        'x-edgeconnect-midmile-rtt': '185',
        'x-edgeconnect-origin-mex-latency': '80',
        date: 'Tue, 10 Sep 2019 02:34:36 GMT',
        connection: 'close' } },
  isOperational: true,
  code: 401,
  body: '{"code":401,"error":"Unauthorized"}',
  headers:
   { 'x-backside-transport': 'FAIL FAIL',
     'content-type': 'application/json',
     'x-dp-transit-id': 'gateway02-695182633',
     'x-global-transaction-id': 'ffea405d5d770bbc296fa529',
     'strict-transport-security': 'max-age=31536000;',
     'x-dp-watson-tran-id': 'gateway02-695182633',
     'content-length': '37',
     'x-edgeconnect-midmile-rtt': '185',
     'x-edgeconnect-origin-mex-latency': '80',
     date: 'Tue, 10 Sep 2019 02:34:36 GMT',
     connection: 'close' } }
(node:8103) UnhandledPromiseRejectionWarning: Unauthorized: Access is denied due to invalid credentials.
    at RequestWrapper.formatError (/Users/zacaintmyname/watson-discovery-news/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
    at /Users/zacaintmyname/watson-discovery-news/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8103) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8103) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by rhagarty** [comment]
@zacaintmyname - make sure you have your DISCOVERY_IAM_APIKEY correctly set in your .env file.

You can find the details here - https://github.com/IBM/watson-discovery-news/blob/master/doc/source/local.md#4-add-watson-discovery-credentials

**Comment by zacaintmyname** [comment]
Hi @rhagarty 

I have included my API key. 

If we take a step back, I think when i do an `npm install`, i get this prompt

audited 1766215 packages in 10.75s
found 5 vulnerabilities (4 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
yeos-mbp:watson-discovery-news zacaintmyname$ npm audit fix
npm WARN babel-loader@8.0.5 requires a peer of webpack@>=2 but none is installed. You must install peer dependencies yourself.

**Comment by rhagarty** [comment]
@zacaintmyname those are warnings and should not be the issue with your invalid credentials.

Try this curl command with your API key:

curl -X GET -u "apikey:XXXXXXX" "https://gateway.watsonplatform.net/discovery/api/v1/environments?version=2019-02-01"

**Comment by zacaintmyname** [comment]
Thank you Sir! 

I found out my mistake, its a very foolish one. Issue closed!
